// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.3 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/deepmap/oapi-codegen/pkg/runtime"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
)

// AuthLoginRequest defines model for AuthLoginRequest.
type AuthLoginRequest struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

// AuthLoginResponse defines model for AuthLoginResponse.
type AuthLoginResponse struct {
	Token string `json:"token"`
}

// Class defines model for Class.
type Class struct {
	// CreatedAt An RFC3339 date/time string
	CreatedAt   DateTime `json:"createdAt"`
	Description string   `json:"description"`
	DisplayName string   `json:"displayName"`

	// Id A cuid
	Id   Cuid   `json:"id"`
	Name string `json:"name"`

	// UpdatedAt An RFC3339 date/time string
	UpdatedAt DateTime `json:"updatedAt"`
}

// ClassList An array of Classes
type ClassList = []Class

// ClassesCreateRequest defines model for ClassesCreateRequest.
type ClassesCreateRequest struct {
	// Description The description of the Class
	Description *string `json:"description,omitempty"`

	// DisplayName The display name of the Class
	DisplayName string `json:"displayName"`

	// Name The name of the Class
	Name *string `json:"name,omitempty"`
}

// ClassesCreateResponse defines model for ClassesCreateResponse.
type ClassesCreateResponse struct {
	Class Class `json:"class"`
}

// ClassesListResponse The response for the /v1/classes endpoint
type ClassesListResponse struct {
	// Classes An array of Classes
	Classes    ClassList      `json:"classes"`
	Pagination PaginationData `json:"pagination"`
}

// ClassesUpdateRequest defines model for ClassesUpdateRequest.
type ClassesUpdateRequest struct {
	// Description The description of the Class
	Description *string `json:"description,omitempty"`

	// DisplayName The display name of the Class
	DisplayName *string `json:"displayName,omitempty"`

	// Name The name of the Class
	Name *string `json:"name,omitempty"`
}

// ClassesUpdateResponse defines model for ClassesUpdateResponse.
type ClassesUpdateResponse struct {
	Class Class `json:"class"`
}

// Cuid A cuid
type Cuid = string

// DateTime An RFC3339 date/time string
type DateTime = string

// Error defines model for Error.
type Error struct {
	// Code The HTTP error code
	Code int `json:"code"`

	// Message A human readable error message
	Message string `json:"message"`
}

// PaginationData defines model for PaginationData.
type PaginationData struct {
	FirstUrl string `json:"firstUrl"`
	LastUrl  string `json:"lastUrl"`
	NextUrl  string `json:"nextUrl"`
	Page     int    `json:"page"`
	PerPage  int    `json:"perPage"`
	PrevUrl  string `json:"prevUrl"`
	Total    int    `json:"total"`
}

// Teacher defines model for Teacher.
type Teacher struct {
	// CreatedAt An RFC3339 date/time string
	CreatedAt DateTime `json:"createdAt"`
	Email     string   `json:"email"`
	FullName  string   `json:"fullName"`

	// Id A cuid
	Id Cuid `json:"id"`

	// UpdatedAt An RFC3339 date/time string
	UpdatedAt DateTime `json:"updatedAt"`
}

// TeacherList An array of Teachers
type TeacherList = []Teacher

// TeachersCreateRequest defines model for TeachersCreateRequest.
type TeachersCreateRequest struct {
	Email    string `json:"email"`
	FullName string `json:"fullName"`
}

// TeachersCreateResponse defines model for TeachersCreateResponse.
type TeachersCreateResponse struct {
	Teacher Teacher `json:"teacher"`
}

// TeachersListResponse The response for the /v1/teachers endpoint
type TeachersListResponse struct {
	Pagination PaginationData `json:"pagination"`

	// Teachers An array of Teachers
	Teachers TeacherList `json:"teachers"`
}

// TeachersUpdateRequest defines model for TeachersUpdateRequest.
type TeachersUpdateRequest struct {
	Email    string `json:"email"`
	FullName string `json:"fullName"`
}

// TeachersUpdateResponse defines model for TeachersUpdateResponse.
type TeachersUpdateResponse struct {
	Teacher Teacher `json:"teacher"`
}

// ClassesListParams defines parameters for ClassesList.
type ClassesListParams struct {
	// PerPage The number of results to retrieve in each page.
	PerPage *int `form:"perPage,omitempty" json:"perPage,omitempty"`

	// Page The page to load.
	Page *int `form:"page,omitempty" json:"page,omitempty"`
}

// TeachersListParams defines parameters for TeachersList.
type TeachersListParams struct {
	// PerPage The number of results to retrieve in each page.
	PerPage *int `form:"perPage,omitempty" json:"perPage,omitempty"`

	// Page The page to load.
	Page *int `form:"page,omitempty" json:"page,omitempty"`
}

// AuthLoginJSONRequestBody defines body for AuthLogin for application/json ContentType.
type AuthLoginJSONRequestBody = AuthLoginRequest

// ClassesCreateJSONRequestBody defines body for ClassesCreate for application/json ContentType.
type ClassesCreateJSONRequestBody = ClassesCreateRequest

// ClassesUpdateJSONRequestBody defines body for ClassesUpdate for application/json ContentType.
type ClassesUpdateJSONRequestBody = ClassesUpdateRequest

// TeachersCreateJSONRequestBody defines body for TeachersCreate for application/json ContentType.
type TeachersCreateJSONRequestBody = TeachersCreateRequest

// TeachersUpdateJSONRequestBody defines body for TeachersUpdate for application/json ContentType.
type TeachersUpdateJSONRequestBody = TeachersUpdateRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Generate a JWT to use as a bearer token for authentication.
	// (POST /v1/auth/login)
	AuthLogin(c *gin.Context)
	// List all classes
	// (GET /v1/classes)
	ClassesList(c *gin.Context, params ClassesListParams)
	// Create a new class
	// (POST /v1/classes)
	ClassesCreate(c *gin.Context)
	// Delete a class by its CUID
	// (DELETE /v1/classes/{id})
	ClassesDelete(c *gin.Context, id Cuid)
	// Get a class by its CUID
	// (GET /v1/classes/{id})
	ClassesGet(c *gin.Context, id Cuid)
	// Update a class by its CUID
	// (PATCH /v1/classes/{id})
	ClassesUpdate(c *gin.Context, id Cuid)
	// List all teachers
	// (GET /v1/teachers)
	TeachersList(c *gin.Context, params TeachersListParams)
	// Create a new teacher
	// (POST /v1/teachers)
	TeachersCreate(c *gin.Context)
	// Delete a teacher by its CUID
	// (DELETE /v1/teachers/{id})
	TeachersDelete(c *gin.Context, id Cuid)
	// Get a teacher by its CUID
	// (GET /v1/teachers/{id})
	TeachersGet(c *gin.Context, id Cuid)
	// Update a teacher by its CUID
	// (PATCH /v1/teachers/{id})
	TeachersUpdate(c *gin.Context, id Cuid)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// AuthLogin operation middleware
func (siw *ServerInterfaceWrapper) AuthLogin(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.AuthLogin(c)
}

// ClassesList operation middleware
func (siw *ServerInterfaceWrapper) ClassesList(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ClassesListParams

	// ------------- Optional query parameter "perPage" -------------

	err = runtime.BindQueryParameter("form", true, false, "perPage", c.Request.URL.Query(), &params.PerPage)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter perPage: %s", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", c.Request.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %s", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.ClassesList(c, params)
}

// ClassesCreate operation middleware
func (siw *ServerInterfaceWrapper) ClassesCreate(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.ClassesCreate(c)
}

// ClassesDelete operation middleware
func (siw *ServerInterfaceWrapper) ClassesDelete(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id Cuid

	err = runtime.BindStyledParameter("simple", false, "id", c.Param("id"), &id)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %s", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.ClassesDelete(c, id)
}

// ClassesGet operation middleware
func (siw *ServerInterfaceWrapper) ClassesGet(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id Cuid

	err = runtime.BindStyledParameter("simple", false, "id", c.Param("id"), &id)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %s", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.ClassesGet(c, id)
}

// ClassesUpdate operation middleware
func (siw *ServerInterfaceWrapper) ClassesUpdate(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id Cuid

	err = runtime.BindStyledParameter("simple", false, "id", c.Param("id"), &id)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %s", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.ClassesUpdate(c, id)
}

// TeachersList operation middleware
func (siw *ServerInterfaceWrapper) TeachersList(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params TeachersListParams

	// ------------- Optional query parameter "perPage" -------------

	err = runtime.BindQueryParameter("form", true, false, "perPage", c.Request.URL.Query(), &params.PerPage)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter perPage: %s", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", c.Request.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %s", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.TeachersList(c, params)
}

// TeachersCreate operation middleware
func (siw *ServerInterfaceWrapper) TeachersCreate(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.TeachersCreate(c)
}

// TeachersDelete operation middleware
func (siw *ServerInterfaceWrapper) TeachersDelete(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id Cuid

	err = runtime.BindStyledParameter("simple", false, "id", c.Param("id"), &id)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %s", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.TeachersDelete(c, id)
}

// TeachersGet operation middleware
func (siw *ServerInterfaceWrapper) TeachersGet(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id Cuid

	err = runtime.BindStyledParameter("simple", false, "id", c.Param("id"), &id)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %s", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.TeachersGet(c, id)
}

// TeachersUpdate operation middleware
func (siw *ServerInterfaceWrapper) TeachersUpdate(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id Cuid

	err = runtime.BindStyledParameter("simple", false, "id", c.Param("id"), &id)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %s", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.TeachersUpdate(c, id)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router *gin.Engine, si ServerInterface) *gin.Engine {
	return RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router *gin.Engine, si ServerInterface, options GinServerOptions) *gin.Engine {

	errorHandler := options.ErrorHandler

	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.POST(options.BaseURL+"/v1/auth/login", wrapper.AuthLogin)

	router.GET(options.BaseURL+"/v1/classes", wrapper.ClassesList)

	router.POST(options.BaseURL+"/v1/classes", wrapper.ClassesCreate)

	router.DELETE(options.BaseURL+"/v1/classes/:id", wrapper.ClassesDelete)

	router.GET(options.BaseURL+"/v1/classes/:id", wrapper.ClassesGet)

	router.PATCH(options.BaseURL+"/v1/classes/:id", wrapper.ClassesUpdate)

	router.GET(options.BaseURL+"/v1/teachers", wrapper.TeachersList)

	router.POST(options.BaseURL+"/v1/teachers", wrapper.TeachersCreate)

	router.DELETE(options.BaseURL+"/v1/teachers/:id", wrapper.TeachersDelete)

	router.GET(options.BaseURL+"/v1/teachers/:id", wrapper.TeachersGet)

	router.PATCH(options.BaseURL+"/v1/teachers/:id", wrapper.TeachersUpdate)

	return router
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xZ72/bNhP+Vwi9L/B+UW05P9DWwIstTbYuRdcEnbMBK/qBFs8WU4lUSCqJV/h/H0j9",
	"tijJiWMj2fzNkMW748Pnjs+dvjs+j2LOgCnpjL870g8gwubnSaKCj3xO2We4SUAq/SwWPAahKJg3IMI0",
	"1D/UIgZn7EglKJs7S9eJsZR3XBDLn0vXEXCTUAHEGX/JbFRWfHXzFXx6Db7S5iqhyJgzCc1YFP8GrN9d",
	"+prNx2mIpWza9QVgBeTEbP+/AmbO2PnPsARtmCE2PMMKJjQCbYuA9AWNFeUmJLjHURxqd++wpD6KsAok",
	"8o1DtwkeoTIO8eITjqC++lezbuSNbKso6YvwNKFEv8kahk1AFwwuggsGNuNJTB6KwgrwlDiZ5/oG62C5",
	"FbyrXlsP7CNNiVlD3DlhCAuBF4jPkHkNNNBUQSR7QTKnsiz8GTuFO5CnJr7WlFg5+XpYkwBQ5YmOTgWQ",
	"Rui4G9LE4ip9AWnU2311koq1Gu822kOoFW5Ud9J60iX0bSXAzzN4jfNdiSBd2uFb86zquQmIyP5FMy4M",
	"KsPb0dBPVyNgJOaUaVJbYob1ojZcN8V1ThnOKda17LJ48wwr3Nh1xZBbRNIBwpXJxz33N+V+H767JXiS",
	"3hwrFRT5iSnZ5b7865Ac+Nf3ged53s1fImJvDkf0tWA28Ip7wFabP/98enh4+Bbp3Q4VjQBlC6vuRm/f",
	"HL/yjl6NDiYHh+MDb3zsDY4P/rQ5+0kILixwcdJygL9MJpcI9CpkXqr4PfKOCg+UKZiD0C4ikBLPbdtB",
	"QRJhhgRggqchZGbz96s7+sQVmvGEkd6CmAWVG7Ed20pqNzY/o0KqKxHWL/pKTfohxnP4v5X5IV5n6aE1",
	"aeD+sUvjDN9i3YHrRJTRKImc8ch2KDGIy8aiY9eJ8H22yvN6bQi4fSRMiitcX/j6uOLOa7pr1l99zPk2",
	"coslimV4bnmg5fnYeDEB7AcgnkjIFgq/xOaaB2xAOPwYLaQfcB4OgCQ2eGZJGDY17AceMHTGYTMJ+0R6",
	"tAjRLfqQ9fVnhnS/As1eXFuC5kdoEaG5qR4VustjW8G1AWkHdL2KTpVkXguw1WYve94VwiOFXWa6Q9k9",
	"XqW5eeDrMiUVhl3irjDYBUWPvOsi1fOhVJ+G2hql9JuUzXiTROdMgcC+QndUBWjBE4H8gIZEAJP/QwWT",
	"MCOaXlSg7OoZaGSoMmBdxMB+MyCjk8tzx3VuQcjU/GjgDTwNAY+B4Zg6Y+fQPNJXqgrMrjVlcaKCYcjn",
	"1BAy5ukZa2wMS86JLlv5oMVJtw1SveNkkaoppoCZNTiOQ+qbVcNrmRI8Ba4P1sZMaVkHWIkEzIP0+Ezs",
	"B563Df8ZQUwAq5Luwx8TpDiaAkokEJP4Gj1gKnM70HgfPWFgqYS1BPM7DikxFlNlqR0f78LxFYP7GHwF",
	"JHe8dB2ZRBEWC2fsvAemiQMI52glEhCWCKMpYAECmVGbFTvXUXgudTrpfzSZR85Xbb6iu3Tcc7BQtNKQ",
	"G4YLHIEytfKLtVdLoikIfQ0LkEmopA5VgBIUbgFRhnT6Ia3EdFw6N5ybBMQin1aNK/KsRLQp7Gy+tVXt",
	"LuSYtFrvNf11i/lgm25YMyKkUmkQ84GGLlblDYMIKExD+VzIqfeDcBjm4VYYVz4xpHNbCmFt5LSlYmid",
	"KK5VEEfbiqGdAprPmTZOUXVRzOMkNA/MxRaBwgQrvK+NKZoIIwZ35QzLTsB61Rt+p2SZKogQFLTy8iz9",
	"u1H/TIXRt35ZYEyjUyeUuy45TLe1cQGqCzD+rSYD03iyojflPATMGqqLf2sRXBaOaoDSMUsh2E+vzs9Q",
	"LPgtJUAyeh5tnyWfeBbNHc4jMomiAqzQ+dngudA1JRPCWbTTBaJKGtC66mbX5fwe1Ivk5hYGrHuWPpng",
	"VA+laIyVH7SSNO0Ud8nTrUmIeue+457K/vFiQ+LvgG+TAAQY1mPtfRpCVOnQKYsTtc/C1SxMT/lhiZhJ",
	"nOpQy3p5VEdy+9Zu0xO2Djj/Sb2dKsfqOfEqjzq7u/r8eUvtnX1Wv+P+rmXS3tPgZTjuW7z1Wrx8KNxO",
	"xJUS2Nvm5ce27/PaqJpB+Ww0dB7PS+n18njtN3izkHbe2C+139vwY9DDer49Yzfo+x5K15bWr/6V8GX3",
	"fvbPtjtu/lo+u26cAv/C/u+F5GPRAT4sJZfL5d8BAAD//8PE6lVsMAAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
